# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='昵称')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='姓氏')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, help_text='是否可以登录到后台管理站点', verbose_name='职员状态')),
                ('is_active', models.BooleanField(default=True, help_text='指明用户是否被认为活跃的。以反选代替删除帐号', verbose_name='有效状态')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('avatar_url', models.ImageField(blank=True, default='avatar/default_big.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像220x220')),
                ('avatar_middle_thumbnall', models.ImageField(blank=True, default='avatar/default_middle.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像104x104')),
                ('avatar_small_thumbnall', models.ImageField(blank=True, default='avatar/default_middle.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像70x70')),
                ('avatar_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像ALT说明')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号码')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('valid_email', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否验证邮箱')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='公司名')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=30, null=True, verbose_name='省份')),
                ('index', models.IntegerField(default=999, verbose_name='按顺序排列(从小到大)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='广告标题')),
                ('description', models.CharField(max_length=200, verbose_name='广告描述')),
                ('image_url', models.ImageField(upload_to='ad/%Y%m', verbose_name='图片路径')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='回调url')),
                ('play', models.BooleanField(default=False, verbose_name='是否播放')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '广告栏',
                'verbose_name_plural': '广告栏',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('EG', '就业指导'), ('TC', '技术干货'), ('WK', '麦子百科'), ('IN', '行业资讯'), ('AV', '官方活动')], default='AV', max_length=10, verbose_name='文章分类')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('desc', models.CharField(max_length=100, verbose_name='文章描述')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('click_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐阅读至首页')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('index', models.IntegerField(default=999, verbose_name='文章排列顺序(从小到大)')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='FriendshipLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='友情链接名称')),
                ('callback_url', models.URLField(verbose_name='url链接地址')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('display', models.BooleanField(default=True, verbose_name='是否主页显示')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='OtherCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='其他课程')),
                ('description', models.TextField(verbose_name='课程介绍')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='课程封面')),
                ('index', models.IntegerField(default=999, verbose_name='职业课程顺序(从小到大)')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('student_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('is_homeshow', models.BooleanField(default=False, verbose_name='是否主页显示')),
                ('search_keywords', models.ManyToManyField(to='common.Keywords', verbose_name='其他课程搜索关键词')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '其他课程',
                'verbose_name_plural': '其他课程',
            },
        ),
        migrations.CreateModel(
            name='PayAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('class_name', models.CharField(max_length=20, verbose_name='类名称')),
                ('callback_url', models.URLField(verbose_name='链接地址')),
                ('index', models.IntegerField(default=999, verbose_name='按顺序排列(从小到大')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '关注我们',
                'verbose_name_plural': '关注我们',
            },
        ),
        migrations.CreateModel(
            name='RecommendedSearchkeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='推荐搜索关键词')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
                ('display', models.BooleanField(default=False, verbose_name='是否显示')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '推荐搜索关键词',
                'verbose_name_plural': '推荐搜索关键词',
            },
        ),
        migrations.CreateModel(
            name='StrategicCooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='战略合作名称')),
                ('callback_url', models.URLField(verbose_name='链接地址')),
                ('image_url', models.ImageField(upload_to='cooperation/%Y/%m', verbose_name='图片')),
                ('index', models.IntegerField(default=999, verbose_name='按顺序排列(从小到大')),
                ('display', models.BooleanField(default=True, verbose_name='是否主页显示')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '战略合作',
                'verbose_name_plural': '战略合作',
            },
        ),
        migrations.CreateModel(
            name='VocationalCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='职业课程')),
                ('description', models.TextField(verbose_name='课程介绍')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='课程封面')),
                ('index', models.IntegerField(default=999, verbose_name='职业课程顺序(从小到大)')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('student_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('search_keywords', models.ManyToManyField(to='common.Keywords', verbose_name='职业课程搜索关键词')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '职业课程',
                'verbose_name_plural': '职业课程',
            },
        ),
    ]
