# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-17 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='广告标题')),
                ('description', models.CharField(max_length=200, verbose_name='广告描述')),
                ('image_url', models.ImageField(upload_to='ad/%Y%m', verbose_name='图片路径')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='回调url')),
                ('play', models.BooleanField(default=False, verbose_name='是否播放')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
            ],
            options={
                'verbose_name': '广告栏',
                'verbose_name_plural': '广告栏',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='OtherCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='其他课程')),
                ('description', models.TextField(verbose_name='课程介绍')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='课程封面')),
                ('index', models.IntegerField(default=999, verbose_name='职业课程顺序(从小到大)')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('student_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('is_homeshow', models.BooleanField(default=False, verbose_name='是否主页显示')),
                ('search_keywords', models.ManyToManyField(to='common.Keywords', verbose_name='其他课程搜索关键词')),
            ],
            options={
                'verbose_name': '其他课程',
                'verbose_name_plural': '其他课程',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedSearchkeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='推荐搜索关键词')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
                ('display', models.BooleanField(default=False, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '推荐搜索关键词',
                'verbose_name_plural': '推荐搜索关键词',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocationalCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='职业课程')),
                ('description', models.TextField(verbose_name='课程介绍')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='课程封面')),
                ('index', models.IntegerField(default=999, verbose_name='职业课程顺序(从小到大)')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('student_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('search_keywords', models.ManyToManyField(to='common.Keywords', verbose_name='职业课程搜索关键词')),
            ],
            options={
                'verbose_name': '职业课程',
                'verbose_name_plural': '职业课程',
                'ordering': ['-id'],
            },
        ),
    ]
