# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节名称')),
                ('video_url', models.CharField(max_length=200, verbose_name='视频资源URL')),
                ('video_length', models.IntegerField(verbose_name='视频长度（秒）')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享次数')),
                ('index', models.IntegerField(default=999, verbose_name='章节顺序(从小到大)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.OtherCourses', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '视频章节',
                'verbose_name': '视频章节',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_small_thumbnall',
            field=models.ImageField(blank=True, default='avatar/default_samll.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像70x70'),
        ),
    ]
