# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_vocationalcourses_seo_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercourses',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO关键词'),
        ),
    ]
