# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_othercourses_seo_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节资源名称')),
                ('download_url', models.FileField(upload_to='lesson/%Y/%m', verbose_name='下载地址')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '章节资源',
                'verbose_name_plural': '章节资源',
            },
        ),
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10, verbose_name='课程ID')),
                ('course_type', models.SmallIntegerField(choices=[(1, '其他'), (2, '职业课程')], verbose_name='课程类型')),
                ('index', models.IntegerField(default=999, verbose_name='课程显示顺序(从小到大)')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '我的课程',
                'verbose_name_plural': '我的课程',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='名字'),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
