# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160924_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='讨论内容')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='父讨论ID')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lesson', verbose_name='章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程讨论',
                'verbose_name_plural': '课程讨论',
            },
        ),
        migrations.CreateModel(
            name='MyFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_favorite', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.OtherCourses', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '我的收藏',
                'verbose_name_plural': '我的收藏',
            },
        ),
        migrations.AlterUniqueTogether(
            name='myfavorite',
            unique_together=set([('user', 'course')]),
        ),
    ]
